### ISSUE TITLE
Declaring CloudInt as local variable?

### ISSUE THREAD

**Issue by Whyser** [jizc/CloudOnce#30]
Hey again, I hope this is okay to ask a general question here.

In the documentation it says: 
> Make sure you don't declare any cloud variables as local variables within your methods, this will mess up the save system.

In what way will it mess up the "save system"? Or is it just that I can't call "Reset" on the instance (since it has left the scope)? In my use case I have no use for the actual instance, I only wanna make sure I save the value (first locally) and than be able to call "Save()" to persist it online. It's probably way more common for people to wanna save their own, already existing variables by Key, rather than having to depend on declaring all variables as CloudInt/String/etc since the beginning.

**Comment by sindrijo** [comment]
You can initialize them by using:
`DataManager.InitializeIntInitializeInt(string key, PersistenceType persistenceType, int value)`

It can be error prone in the current implementation to use CloudInt/String/X.. to do this because `CloudOnce.Internal.DataManager` expects there only to be one instance per key, initializing a CloudInt with a key say "A" will override an existing CloudInt registered with key "A" and will stop receiving updates from the DataManager, this a quite painful side-effect.

This can probably be made less painful/more robust if the DataManager could know about more than one instance of a key at a time (and could therefore notify all of the instances when a change has happened, however it would also be required to propagate changes to all other instances of CloudInt when one of them changes the value.) so it would probably mean a substantial change to the current system.

**Comment by jizc** [comment]
I'm not certain this is correct anymore. I'll do a couple tests and get back to you.

**Comment by jizc** [comment]
@sindrijo is correct here. But if you only want to set the value and then save, I think it should be fine to declare them locally. Just know that it wasn't designed to be used that way and there is no guaranty that the system will work correctly.

**Comment by Whyser** [comment]
Thanks!
